  <?php

  function my_database_theme($existing, $type, $theme, $path): array {
    return [
      'yearly_dashboard' => [
        'variables' => [
          'yearly_event' => NULL
        ],
      ],
      
      'quarterly_dashboard' => [
        'variables' => [
          'quarters' => NULL,
          'event_no'=> NULL,
        ],
      ],

      'type_dashboard' => [
        'variables' => [
          'type_event' => NULL
        ],
      ]
    ];
  }
