custom_entity.movie_configuration:
  type: custom_entity
  label: 'Movie Configuration'
  mapping:
    id:
      type: string
      label: ID
    label:
      type: label
      label: Label
    uuid:
      type: string
    description:
      type: string
      